// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2JZ279S03t6vHfzIvp_c5sCzDxLvW9po',
    appId: '1:948601270698:web:74dc870d0eda2da8c1fbd3',
    messagingSenderId: '948601270698',
    projectId: 'chat-app-752cc',
    authDomain: 'chat-app-752cc.firebaseapp.com',
    storageBucket: 'chat-app-752cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZDOO-9hy6pEOUiwlZ_ao8Lqa7Vw-M9wo',
    appId: '1:948601270698:android:7b5d63b0c4750a50c1fbd3',
    messagingSenderId: '948601270698',
    projectId: 'chat-app-752cc',
    storageBucket: 'chat-app-752cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVwYFUK421f3UeC0pHdgQNlGMHZ924WrY',
    appId: '1:948601270698:ios:5f30233bd6f90aa0c1fbd3',
    messagingSenderId: '948601270698',
    projectId: 'chat-app-752cc',
    storageBucket: 'chat-app-752cc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVwYFUK421f3UeC0pHdgQNlGMHZ924WrY',
    appId: '1:948601270698:ios:5f30233bd6f90aa0c1fbd3',
    messagingSenderId: '948601270698',
    projectId: 'chat-app-752cc',
    storageBucket: 'chat-app-752cc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2JZ279S03t6vHfzIvp_c5sCzDxLvW9po',
    appId: '1:948601270698:web:22e7254f0f538db5c1fbd3',
    messagingSenderId: '948601270698',
    projectId: 'chat-app-752cc',
    authDomain: 'chat-app-752cc.firebaseapp.com',
    storageBucket: 'chat-app-752cc.firebasestorage.app',
  );
}
